spring.application.name=order-service
# Connection URL format: jdbc:h2:mem:[database_name]
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver

# Enables the H2 web console interface at http://localhost:8080/h2-console
spring.h2.console.enabled=true 
